from duckduckgo_search import DDGS

import google.generativeai as genai

async def fetch_market_data(sector: str):
    try:
        query = f"{sector} industry India growth trends news"

        with DDGS() as ddgs:
            results = list(ddgs.text(query, max_results=5))

        snippets = [r.get("body", "") for r in results if r.get("body")]

        if not snippets:
            raise Exception("No data found")

        return "\n\n".join(snippets[:3])

    except Exception:
        return f"""
Recent observations for {sector} sector in India:

- Increasing investment and government support
- Growing domestic demand
- Expansion in infrastructure and digital capabilities
- Rising global competitiveness
"""


async def generate_analysis(sector: str, data: str):
    try:
        client = genai.Client()

        prompt = f"""
You are a financial market analyst.

Based on the following real-time data:

{data}

Generate a detailed report on the {sector} sector in India.

Include:
1. Current Trends
2. Trade Opportunities
3. Risks
4. Future Outlook

Make it analytical and insightful.
"""

        response = client.models.generate_content(
            model="gemini-1.5-flash",
            contents=prompt
        )

        print("Gemini SUCCESS")

        return response.text or "No analysis generated"

    except Exception as e:
        print("Gemini FAILED:", str(e))

        return f"""
### Current Trends
{data[:400]}

### Trade Opportunities
- Growing demand in {sector}
- Policy and investment support
- Expansion opportunities

### Risks
- Market volatility
- Regulatory uncertainty
- Global dependency

### Future Outlook
The {sector} sector shows promising growth potential.
"""


def build_markdown(sector: str, analysis: str):
    return f"""
# Trade Opportunities Report: {sector.title()}

## Overview
Insights for the {sector} sector in India.

## Analysis
{analysis}

## Conclusion
Potential opportunities exist depending on market conditions.

---
Generated by Trade Opportunities API
"""
